config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/sign_in" => "devise/sessions#new"
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration"
  end
  
  devise_for :users
  
  resources :wikis do
    get '/collaborator' => 'wikis#collaborator'
    post '/add' => 'wikis#add', as: :add
    get '/collaborator_remove' => 'wikis#collaborator_remove'
    delete '/remove' => 'wikis#remove', as: :remove
  end
  
  resources :charges, only: [:new, :create]
  
  resources :users do
    post '/downgrade' => 'users#downgrade', as: :downgrade
  end
  
  get 'welcome/about'
  
  authenticated :user do
    root to: 'wikis#index', as: :authenticated_root
  end

  root 'welcome#index'
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
    belongs_to :user
    belongs_to :wiki
    
    validates_uniqueness_of :user_id, scope: [:wiki_id]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :collaborators
  has_many :wikis, through: :collaborators, dependent: :destroy
  
  after_initialize { self.role ||= :standard }
  
  after_commit :assign_customer_id, on: :create
  
  enum role: { standard: 0, premium: 1, admin: 2 }
  
  def assign_customer_id
    customer = Stripe::Customer.create(email: email)
    self.customer_id = customer.id
  end
  
  def make_wikis_public
    @wikis = Wiki.where(user_id: self.id).all
    @wikis.each do |wiki|
      wiki.update_attribute(:private, false)
    end
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  has_many :collaborators
  has_many :users, through: :collaborators
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  
  # def after_sign_in_path_for(resource)
  #   request.env['omniauth.origin'] || stored_location_for(resource) || root_path
  # end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    before_action :authenticate_user!
    
    def create
        customer = Stripe::Customer.create(
            email: current_user.email,
            card: params[:stripeToken]
            
        )
        # current_user.update(customer_id: @customer.id)
        charge = Stripe::Charge.create(
            customer: customer.id,
            amount: 1500,
            description: "Blocipedia Premium Membership - #{current_user.email}",
            currency: 'usd'
        )
        current_user.premium!
        
        flash[:notice] = "Thanks for all the money, #{current_user.email}!"
        
        redirect_to wikis_path
        
        rescue Stripe::CardError => e
            flash[:alert] = e.message
            redirect_to new_charge_path
    end
    
    def new
        @stripe_btn_data = {
            key: "#{ Rails.configuration.stripe[:publishable_key]}",
            description: "Blocipedia Membership - #{current_user.email}",
            amount: 1500
        }
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
    
    def create
        @user = User.new
        @user.name = params[:user][:name]
        @user.email = params[:user][:email]
        @user.password = params[:user][:password]
        @user.password_confirmation = params[:user][:password_confirmation]
        
        if @user.save
            flash[:notice] = "Welcome to Blocipedia, #{@user.name}!"
            redirect_to root_path
        else
            flash.now[:alert] = "There was an error creating your account. Please try again."
            render :new
        end
    end
    
    def downgrade
        @user = User.find(params[:user_id])
        @user.role = "standard"
        @user.make_wikis_public
        
        
        if @user.save
            flash[:notice] = "You have been downgraded, #{@user.email}"
            redirect_to root_path
        else
            flash.now[:alert] = "There was an error downgrading your profile. Please try again."
            render :new
        end
    end
        
    # def show
    #     @user = User.find(params[:id])
    # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
    def index
        @wikis = policy_scope(Wiki)
    end
    
    def new
        @wiki = Wiki.new
    end
    
    def create
        @wiki = Wiki.new
        @wiki.title = params[:wiki][:title]
        @wiki.body = params[:wiki][:body]
        @wiki.private = params[:wiki][:private]
        @wiki.user_id = current_user.id
        
        if @wiki.save
            flash[:notice] = "Wiki was saved successfully!"
            redirect_to @wiki
        else
            flash[:alert] = "There was an error saving the wiki. Please try again."
            render :new
        end
    end
    
    def show
        @wiki = Wiki.find(params[:id])
    end
    
    def edit
        @wiki = Wiki.find(params[:id])
    end
    
    def update
        @wiki = Wiki.find(params[:id])
        @wiki.title = params[:wiki][:title]
        @wiki.body = params[:wiki][:body]
        @wiki.private = params[:wiki][:private]
        if @wiki.save
            flash[:notice] = "Wiki was saved successfully!"
            redirect_to @wiki
        else
            flash[:alert] = "There was an error saving the wiki. Please try again."
            render :edit
        end
    end
    
    def destroy
        @wiki = Wiki.find(params[:id])
        if @wiki.destroy
            flash[:notice] = "The wiki was deleted successfully."
            redirect_to action: :index
        else
            flash[:alert] = "There was an error deleting the wiki. Please try again."
            render :show
        end
    end
    
    def collaborator
        @wiki = Wiki.find(params[:wiki_id])
    end
    
    def add
        @user = User.where(email: params[:user_email]).first
        @wiki = Wiki.find(params[:wiki_id])
        if User.exists?(:email => params[:user_email])
            @collaborator = Collaborator.new
            @collaborator.user_id = @user.id
            @collaborator.wiki_id = @wiki.id
            
            if @collaborator.save
                flash[:notice] = "You can now collaborate with #{@user.email} on this wiki!"
                redirect_to @wiki
            else
                flash[:alert] = "You might have added this collaborator already. Please try again."
                render :show
            end
        else
            flash[:alert] = "That's not a valid email. Please try again."
            render :show
        end
    end
    
    def collaborator_remove
        @wiki = Wiki.find(params[:wiki_id])
    end
    
    def remove
        @user = User.where(email: params[:user_email]).first
        @wiki = Wiki.find(params[:wiki_id])
        @collaborators = Collaborator.where("user_id = ? AND wiki_id = ?", @user.id, @wiki.id).first
        
        if @collaborators.destroy
            flash[:notice] = "#{@user.email} can no longer work on this wiki."
            redirect_to @wiki
        else
            flash[:alert] = "There was an error deleting the collaborator. Please try again."
            render :show
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    require 'redcarpet'

    def markdown(text)
        renderer = Redcarpet::Render::HTML.new
        markdown = Redcarpet::Markdown.new(renderer, autolink: true, tables: true)
        markdown.render(text).html_safe
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
 <%= form_tag charges_path do %>
   <h4>Upgrade to Premium for only $15!</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <div class="pull-left user-info">
        <%= link_to "Wikis", wikis_path, class: "btn btn-default" %>
        <% if user_signed_in? && current_user.role == "standard" %>
          <%= link_to "Upgrade to Premium", new_charge_path, class: "btn btn-primary" %>
        <% elsif user_signed_in? && current_user.role == "premium" %>
          <%= link_to "Downgrade to Standard", user_downgrade_path(current_user), :data => {:confirm => 'Are you sure?'}, class: "btn btn-primary", method: :post %>
        <% end %>
      </div>
      <div class="pull-right user-info">
        <% if user_signed_in? %>
          <%= "Hello #{current_user.email}" %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-warning" %>
        <% else %>
          <%= link_to "Sign in", new_user_session_path, class: "btn btn-default" %>
        <% end %>
      </div>
    </ul>
    <% if flash[:notice] %>
     <div class="alert alert-success">
       <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash[:notice] %>
     </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
  <%= yield %>
  </div>
</body>
</html>

app/views/users/new.html.erb
<h2>Sign up</h2>
 
 <div class="row">
   <div class="col-md-8">
     <%= form_for @user do |f| %>
       <% if @user.errors.any? %>
         <div class="alert alert-danger">
           <h4><%= pluralize(@user.errors.count, "error") %>.</h4>
           <ul>
             <% @user.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
             <% end %>
           </ul>
         </div>
       <% end %>
       <%= form_group_tag(@user.errors[:name]) do %>
         <%= f.label :name %>
         <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "Enter name" %>
       <% end %>
       <%= form_group_tag(@user.errors[:email]) do %>
         <%= f.label :email %>
         <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
       <% end %>
       <%= form_group_tag(@user.errors[:password]) do %>
         <%= f.label :password %>
         <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
       <% end %>
       <%= form_group_tag(@user.errors[:password_confirmation]) do %>
         <%= f.label :password_confirmation %>
         <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password confirmation" %>
       <% end %>
       <div class="form-group">
         <%= f.submit "Sign up", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
    <h1>Blocipedia</h1>
    <p>Blocipedia is a resource for sharing resource with your friends!</p>
    <p>
        <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
    </p>
</div>

app/views/wikis/_form.html.erb
<div>
    <%= form_for @wiki do |f| %>
        <div class="form group">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control', placeholder: 'Enter wiki title' %>
        </div>
        <div class="form-group">
            <%= f.label :body %>
            <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
        </div>
        <% if current_user.admin? || current_user.premium? %>
            <div class="form-group">
                <%= f.label :private, class: 'checkbox' do %>
                    <%= f.check_box :private %> Private wiki
                <% end %>
            </div>
        <% end %>        
        
        <div class="form-group">
            <%= f.submit "Save", class: 'btn btn-success' %>
        </div>
    <% end %>
</div>

app/views/wikis/collaborator.html.erb
<h1>Add Collaborator!</h1>

<%= form_tag wiki_add_path do %>
    <label for="user_email">Enter user email</label>
    <%= text_field_tag :user_email %>
    <%= submit_tag("Submit") %>
<% end %>

app/views/wikis/collaborator_remove.html.erb
<h1>Remove Collaborator!</h1>

<%= form_tag wiki_remove_path, :method => 'delete' do %>
    <label for="user_email">Enter user email</label>
    <%= text_field_tag :user_email %>
    <%= submit_tag("Submit") %>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<%= render partial: "form", locals: { wiki: @wiki } %>

app/views/wikis/index.html.erb
 <h1>All Wikis</h1>
 <% @wikis.each do |wiki| %>
   <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <%= link_to wiki.title, wiki %>
       </h4>
     </div>
   </div>
 <% end %>
 <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<%= render partial: "form", locals: { wiki: @wiki } %>

app/views/wikis/show.html.erb
<div>
    <h1>
        <%= @wiki.title %> <br>
    </h1>
</div>

<div class="row">
    <div class="col-md-8">
        <p><%= markdown(@wiki.body) %></p>
    </div>
    <div class="col-md-4">
        <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
        <%= link_to "Delete Wiki", [@wiki], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
    </div>
</div>

<div>
    <% if !(@wiki.private?) || @wiki.user_id == current_user.id || @wiki.collaborators.include?(@user) %>
        <%= link_to "Add collaborators", wiki_collaborator_path(@wiki.id), class: 'btn btn-success' %>
        <%= link_to "Remove collaborators", wiki_collaborator_remove_path(@wiki.id), class: 'btn btn-danger' %>
    <% end %>
</div>